spring.application.name=ccsp
server.port=8080

# Logging configuration
logging.level.root=INFO
logging.level.com.ccsp=DEBUG

# Save logs to file
logging.file.name=logs/ccsp-application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

#
#file.upload-dir=./vscode_expermints/expermintalDownloads

# Prevent Spring from caching the whole file into RAM/Temp disk automatically
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=0

# Allow large files to pass through the network layer without throwing SizeExceptions
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

# assigning uploading and downloading path 
upload.dir = /home/rahq05/gitHub_files/CCSP-CloudStorage/uploads

# array of bytes buffer size 
buffer.size.upload = 8192
buffer.size.download= 8192

# Enable the H2 browser console
spring.h2.console.enabled=true

# The URL path to access the console
spring.h2.console.path=/h2

# The in-memory database name (you choose the name after "mem:") + uncomment the other line for nonvolatile saving
spring.datasource.url=jdbc:h2:mem:Files_List
#spring.datasource.url=jdbc:h2:file:/data/demo

# Driver class Spring uses to talk to the H2 database
spring.datasource.driverClassName=org.h2.Driver

# Username used to authenticate with the datasource
spring.datasource.username=sa

# Password used to authenticate with the datasource
spring.datasource.password=password

# Tells Hibernate which SQL dialect to generate queries in (H2-specific syntax/optimizations)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# so tables updates and get created
spring.jpa.hibernate.ddl-auto=update

