spring.application.name=ccsp
server.port=8080

# Logging configuration
logging.level.root=INFO
logging.level.com.ccsp=DEBUG

# Save logs to file
logging.file.name=logs/ccsp-application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

#
#file.upload-dir=./vscode_expermints/expermintalDownloads

# Prevent Spring from caching the whole file into RAM/Temp disk automatically
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=0

# Allow large files to pass through the network layer without throwing SizeExceptions
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

# assigning uploading and downloading path 
upload.dir = /home/rahq05/gitHub_files/CCSP-CloudStorage/uploads

# array of bytes buffer size 
buffer.size.upload = 8192
buffer.size.download= 8192
